---
### Model I: KEAP1-dependent NRF2 sequestration and degradation
### Unit: time = second, concentration = nM
---
  
```{r}
# Load Package
library(deSolve)
```


```{r}
## ---------------------------------
## Parameter values
## --------------------------------- 
parameters_default <- c(
  S = 0,
  k0 	= 0.15,
  kf 	= 0.01,
  kb 	= 0.01,
  k1 	= 2.888E-4,
  k2 	= 1.775E-3,
  Kd1 = 7
)
parameters <- parameters_default

## ----------------------------------
## Initial conditions
## ----------------------------------
y0 <- c(
  NRF2_free 	= 0,
  KEAP1			  = 200,
  KEAP1_NRF2 	= 0
)

## ----------------------------------
## Differential equations to solve
## ----------------------------------
Model_I <- function(times, y, parms)
{
  with(as.list(c(y, parms)),
       {
         #ODEs for the state variables
         dNRF2_freedt		=  k0 - kf * KEAP1 * NRF2_free + kb * KEAP1_NRF2 - k1 * NRF2_free
         dKEAP1dt		= - kf * KEAP1 * NRF2_free + kb * KEAP1_NRF2 + Kd1 / (Kd1 + S) * k2 * KEAP1_NRF2
         dKEAP1_NRF2dt	= kf * KEAP1 * NRF2_free - kb * KEAP1_NRF2 - Kd1 / (Kd1 + S) * k2 * KEAP1_NRF2
         list(c(dNRF2_freedt, dKEAP1dt, dKEAP1_NRF2dt)); #Return simulated value of state variables at each time step
       })
}

## ----------------------------------
## Run simulation
## ----------------------------------
#Time span of simulation
tspan <- seq(0, 108000, by = 100)
#Call the lsoda function to numerically solve the ODEs
output <- lsoda(y = y0, times = tspan, func = Model_I, parms = parameters)
#Optional: show the result of the first 6 time steps
head(output)
```


```{r}
## ----------------------------------
## Plotting simulation results
## ----------------------------------
par(mar = c(5, 5, 1, 1), mgp = c(2, 0.5, 0)) # mar(figure margins):bottom, left, top, right; mgp(label position): distance from label, scale, tick marks to plot 
plot(output, xlab = "Time (S)", las=1, cex.lab=1.4, cex.axis=1.3, col="blue", lwd = 2)
```


```{r}
## Dose Response (Fig. 2B)
## -------------------------------------
logdose <- seq(-1,3, by = 0.05)
dose <- 10^logdose

NRF2_free_ss <- c()  #A vector to hold steady-state NRF2_free values
KEAP1_ss <- c()  #A vector to hold steady-state KEAP1 values
KEAP1_NRF2_ss <- c()  #A vector to hold steady-state KEAP1_NRF2 values

for( i in dose)
{
  parameters["S"]=i
  output <- lsoda(y = y0, times = tspan, func = Model_I, parms = parameters)
  lastpoint_index <- length(output[,"time"])
  NRF2_free_ss <- c(NRF2_free_ss,output[lastpoint_index,"NRF2_free"])
  KEAP1_ss <- c(KEAP1_ss,output[lastpoint_index,"KEAP1"])
  KEAP1_NRF2_ss <- c(KEAP1_NRF2_ss,output[lastpoint_index,"KEAP1_NRF2"])
}
  NRF2tot_ss = NRF2_free_ss + KEAP1_NRF2_ss 

plot(dose, NRF2_free_ss, lwd = 2, log="xy", xlim = c(0.1, 1000), ylim = c(0.1, 1000), xlab="S", ylab ="", cex.lab =1.4, cex.axis=1.3, las=0.5, 'l', pch=20, col="blue") 

par(new=TRUE)
plot(dose, KEAP1_ss, lwd = 2, log="xy", xlim = c(0.1, 1000), ylim = c(0.1, 1000), xlab="S", ylab ="", cex.lab =1.4, cex.axis=1.3, las=0.5,'l', pch=20, col="green") 

par(new=TRUE)
plot(dose, KEAP1_NRF2_ss, lwd = 2, log="xy", xlim = c(0.1, 1000), ylim = c(0.1, 1000), xlab="S", ylab ="", cex.lab =1.4, cex.axis=1.3, las=0.5, 'l', pch=20, col="purple")

par(new=TRUE)
plot(dose, NRF2tot_ss, lwd = 2, log="xy", xlim = c(0.1, 1000), ylim = c(0.1, 1000), xlab="S", ylab ="", cex.lab =1.4, cex.axis=1.3, las=0.5, 'l', pch=20, col="orange")

title(ylab="Protein Levels (nM)", line=2.5, cex.lab=1.4)
grid()
legend(60,20, legend=c("NRF2_free", "KEAP1","KEAP1-NRF2", "NRF2_tot"), col=c("blue", "green","purple", "orange") , lty=1, cex=1)

```


```{r}
## Dose Response (Fig. 2C)
## -------------------------------------

logdose <- seq(-1,3, by = 0.05)
dose <- 10^logdose

parameters["kf"]= 0.01 * 0.2  # default=0.01
NRF2_free_ss <- c()  
for( i in dose)
{
  parameters["S"]=i
  output <- lsoda(y = y0, times = tspan, func = Model_I, parms = parameters)
  lastpoint_index <- length(output[,"time"])
  NRF2_free_ss <- c(NRF2_free_ss,output[lastpoint_index,"NRF2_free"])
}
plot(dose, NRF2_free_ss, lwd = 2, 'l', log="xy", xlim = c(0.1, 1000), ylim = c(0.1, 1000), xlab="S", ylab ="", cex.lab =1.4, cex.axis=1.3, las=0.5, pch=20, col="cyan") 
title(main="NRF2_free")


parameters["kf"]= 0.01 * 1 # default=0.01
NRF2_free_ss <- c()  
for( i in dose)
{
  parameters["S"]=i
  output <- lsoda(y = y0, times = tspan, func = Model_I, parms = parameters)
  lastpoint_index <- length(output[,"time"])
  NRF2_free_ss <- c(NRF2_free_ss,output[lastpoint_index,"NRF2_free"])
}

par(new=TRUE)
plot(dose, NRF2_free_ss, lwd = 2, 'l', log="xy", xlim = c(0.1, 1000), ylim = c(0.1, 1000), xlab="S", ylab ="", cex.lab =1.4, cex.axis=1.3, las=0.5, pch=20, col="blue") 


parameters["kf"]= 0.01 * 5 # default=0.01
NRF2_free_ss <- c()  
for( i in dose)
{
  parameters["S"]=i
  output <- lsoda(y = y0, times = tspan, func = Model_I, parms = parameters)
  lastpoint_index <- length(output[,"time"])
  NRF2_free_ss <- c(NRF2_free_ss,output[lastpoint_index,"NRF2_free"])
}

par(new=TRUE)
plot(dose, NRF2_free_ss, lwd = 2, 'l', log="xy", xlim = c(0.1, 1000), ylim = c(0.1, 1000), xlab="S", ylab ="", cex.lab =1.4, cex.axis=1.3, las=0.5, pch=20, col="black") 

title(ylab="Protein Levels (nM)", line=2.5, cex.lab=1.4)
grid()
legend(60,20, legend=c(" kf x 0.2  ", " kf x 1* ", " kf x 5 "), col=c("cyan", "blue", "black") , lty=1, cex=1)
```


```{r}
## Dose Response (Fig. 2D)
## -------------------------------------
logdose <- seq(-1,3, by = 0.05)
dose <- 10^logdose

parameters <- parameters_default

y0["KEAP1"]= 200 * 0.5 # default = 200
NRF2_free_ss <- c()  
for( i in dose)
{
  parameters["S"]=i
  output <- lsoda(y = y0, times = tspan, func = Model_I, parms = parameters)
  lastpoint_index <- length(output[,"time"])
  NRF2_free_ss <- c(NRF2_free_ss,output[lastpoint_index,"NRF2_free"])
}

plot(dose, NRF2_free_ss, lwd = 2, 'l', log="xy", xlim = c(0.1, 1000), ylim = c(0.1, 1000), xlab="S", ylab ="", cex.lab =1.4, cex.axis=1.3, las=0.5, pch=20, col="cyan") 
title(main="NRF2_free")


y0["KEAP1"]= 200 * 1 # default = 200
NRF2_free_ss <- c()  
for( i in dose)
{
  parameters["S"]=i
  output <- lsoda(y = y0, times = tspan, func = Model_I, parms = parameters)
  lastpoint_index <- length(output[,"time"])
  NRF2_free_ss <- c(NRF2_free_ss,output[lastpoint_index,"NRF2_free"])
}

par(new=TRUE)
plot(dose, NRF2_free_ss, lwd = 2, 'l', log="xy", xlim = c(0.1, 1000), ylim = c(0.1, 1000), xlab="S", ylab ="", cex.lab =1.4, cex.axis=1.3, las=0.5, pch=20, col="blue") 


y0["KEAP1"]= 200 * 2 # default = 200
NRF2_free_ss <- c()  
for( i in dose)
{
  parameters["S"]=i
  output <- lsoda(y = y0, times = tspan, func = Model_I, parms = parameters)
  lastpoint_index <- length(output[,"time"])
  NRF2_free_ss <- c(NRF2_free_ss,output[lastpoint_index,"NRF2_free"])
}

par(new=TRUE)
plot(dose, NRF2_free_ss, lwd = 2, 'l', log="xy", xlim = c(0.1, 1000), ylim = c(0.1, 1000), xlab="S", ylab ="", cex.lab =1.4, cex.axis=1.3, las=0.5, pch=20, col="black") 

title(ylab="Protein Levels (nM)", line=2.5, cex.lab=1.4)
grid()
legend(40,20, legend=c(" KEAP1_tot x 0.5  ", " KEAP1_tot x 1* ", " KEAP1_tot x 2 "), col=c("cyan", "blue", "black") , lty=1, cex=1)
```


