<Document>
<Version> 22 </Version>
<JMadonnaVersion> 10.2.8 </JMadonnaVersion>
<Bounds> 0 0 1424 739 </Bounds>
<NotesEditor>
<jeditorpane>
<size>12</size><family>ËÎÌו</family>



</jeditorpane>
</NotesEditor>
<jmadonna.EquationPanel>
<DocPanel>
</DocPanel>
<jeditorpane>
<size>18</size><family>Serif</family>{Model III: Positive autoregulation of NRF2 and sMaf via transcriptional self-induction}
;Unit: time = second, concentration = nM

METHOD STIFF
STARTTIME = 0
STOPTIME = 3600 * 100
DT = 0.02
Minute = Time / 60

{Parameters}
S = 0
k10 = 7 * logn(2) / (10 * 60)
k1 = 65 * logn(2) / (10 * 60)
k2 = logn(2) / (10 * 60)
k3 = logn(2) / (100 * 60)
k40 = 6 * logn(2) / (100 * 60)
k4 = 83 * logn(2) / (100 * 60)
k5 = logn(2) / (100 * 60)
k6 = logn(2) / (100 * 60)
k7 = 0.001
k8 = 0.1
Kd1 = 20
Kd2 = 1.5
Kd4 = 20

{Inintial condition}
init NRF2 = 1
init sMAF = 10
init NRF2_sMAF = 1

{ODES}
NRF2' = k10 + k1 * NRF2_sMAF / (Kd1 + NRF2_sMAF) - k2 * Kd2 / (Kd2 + S) * NRF2 - k3 * NRF2 - k7 * NRF2 * sMAF + k8 * NRF2_sMAF
;To disable NRF2 auto-induction
;NRF2' = k10 + k1 * 1 / (Kd1 + 1) - k2 * Kd2 / (Kd2 + S) * NRF2 - k3 * NRF2 - k7 * NRF2 * sMAF + k8 * NRF2_sMAF

sMAF' = k40 + k4 * NRF2_sMAF / (Kd4 + NRF2_sMAF) - k5 * sMAF  - k7 * NRF2 * sMAF + k8 * NRF2_sMAF
;To disable sMaf auto-induction
;sMAF' = k40 + k4 * 1 / (Kd4 + 1) - k5 * sMAF  - k7 * NRF2 * sMAF + k8 * NRF2_sMAF

NRF2_sMAF' = - k6 * NRF2_sMAF + k7 * NRF2 * sMAF - k8 * NRF2_sMAF

{Composite variables}
NRF2_tot = NRF2 + NRF2_sMAF
sMAF_tot = sMAF + NRF2_sMAF















<size>12</size>

</jeditorpane>
</jmadonna.EquationPanel>

<imethod> stiff </imethod>
<jmadonna.ParameterPanel>
<DocPanel>
</DocPanel>
<ParamSets>
</ParamSets>
</jmadonna.ParameterPanel>
<jmadonna.MultiPanel>
<DocPanel>
</DocPanel>
<DividerPercent> 1.0 </DividerPercent>
<Orientation> -1 </Orientation>
<idx> 0 </idx>
<TabSplitter>
<SelectedIndex> 1 </SelectedIndex>
<graph.COutputFrame>
<DocPanel>
<Name>
Graph 0
</Name>
</DocPanel>

<SingleView>
<graph.COutputView>
<Name> Graph </Name>
<GraphToolBar>
<Legend> 1 </Legend>
<Grid> 1 </Grid>
</GraphToolBar>
<Plot>
<LineWidth> 1 </LineWidth>
</Plot>
<OV_XVAR>
<VI_SYMBOL> TIME </VI_SYMBOL>
</OV_XVAR>
<OV_YVARS>
<OV_YVAR_I>
<VI_SYMBOL> Minute </VI_SYMBOL>
<VI_SHOW> false </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> NRF2 </VI_SYMBOL>
<VI_SHOW> false </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> sMAF </VI_SYMBOL>
<VI_SHOW> false </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> NRF2_sMAF </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
</OV_YVARS>
<OV_TABLE> false </OV_TABLE>
<OV_FFT> false </OV_FFT>
<OV_COLORS> true </OV_COLORS>
<OV_STYLES> false </OV_STYLES>
<OV_OSCMODE> false </OV_OSCMODE>
<OV_LINES> true </OV_LINES>
<OV_POINTS> true </OV_POINTS>
<OV_GRID> true </OV_GRID>
<OV_DBTN> true </OV_DBTN>
<OV_LEGEND> true </OV_LEGEND>
<OV_PARAMS> false </OV_PARAMS>
<OV_READOUT> false </OV_READOUT>
<OV_INITCOND> false </OV_INITCOND>
<OV_RDOUTFXFY> 0.0 0.0 </OV_RDOUTFXFY>
<OV_ZSNORMAL>
</OV_ZSNORMAL>
<OV_ZSFFT>
<ZS_SIZE> 1 </ZS_SIZE>
<ZS_I>
<ZS_XLOG> true </ZS_XLOG>
<ZS_Y1LOG> false </ZS_Y1LOG>
<ZS_Y2LOG> false </ZS_Y2LOG>
</ZS_I>
</OV_ZSFFT>
<OV_ZSOSCMODE>
</OV_ZSOSCMODE>
<OV_AUTOLABEL> 0 1 </OV_AUTOLABEL>
<OV_AUTOLABEL> 1 1 </OV_AUTOLABEL>
<OV_AUTOLABEL> 2 1 </OV_AUTOLABEL>
<OV_X1LABELS>  TIME </OV_X1LABELS>
<OV_Y1LABELS>  NRF2_sMAF </OV_Y1LABELS>
<OV_Y2LABELS>   </OV_Y2LABELS>
<OV_LEGENDXY> 0.495181 0.376068 </OV_LEGENDXY>
<OV_PARAMSXY> 0.495181 0.376068 </OV_PARAMSXY>
<OV_COLORTABLE> 0 <OV_COLORTABLE>
</graph.COutputView>
</SingleView>
</graph.COutputFrame>
<graph.COutputFrame>
<DocPanel>
<Name>
Parameter Plot...
</Name>
</DocPanel>
<ivar> S </ivar>
<paramGraph>
<nRuns> 40 </nRuns>
<initValue> 0.1 </initValue>
<finalValue> 100.0  </finalValue>
<isArithmetic> 0 </isArithmetic>
<selectedParam> S </selectedParam>
<yvarmodel> !24!@1@#1#$!25!@1@#2#$!26!@1@#3#$!30!@1@#7#$!31!@1@#8#$%$ </yvarmodel>
</paramGraph>

<SingleView>
<graph.COutputView>
<Name> Graph </Name>
<GraphToolBar>
<Grid> 1 </Grid>
</GraphToolBar>
<Plot>
<LineWidth> 1 </LineWidth>
</Plot>
<OV_TABLE> false </OV_TABLE>
<OV_FFT> false </OV_FFT>
<OV_COLORS> true </OV_COLORS>
<OV_STYLES> false </OV_STYLES>
<OV_OSCMODE> false </OV_OSCMODE>
<OV_LINES> true </OV_LINES>
<OV_POINTS> true </OV_POINTS>
<OV_GRID> true </OV_GRID>
<OV_DBTN> true </OV_DBTN>
<OV_LEGEND> false </OV_LEGEND>
<OV_PARAMS> false </OV_PARAMS>
<OV_READOUT> false </OV_READOUT>
<OV_INITCOND> false </OV_INITCOND>
<OV_RDOUTFXFY> 0.0 0.0 </OV_RDOUTFXFY>
<OV_ZSNORMAL>
<ZS_SIZE> 1 </ZS_SIZE>
<ZS_I>
<ZS_XLOG> true </ZS_XLOG>
<ZS_Y1LOG> true </ZS_Y1LOG>
<ZS_Y2LOG> false </ZS_Y2LOG>
</ZS_I>
</OV_ZSNORMAL>
<OV_ZSFFT>
<ZS_SIZE> 1 </ZS_SIZE>
<ZS_I>
<ZS_XLOG> true </ZS_XLOG>
<ZS_Y1LOG> false </ZS_Y1LOG>
<ZS_Y2LOG> false </ZS_Y2LOG>
</ZS_I>
</OV_ZSFFT>
<OV_ZSOSCMODE>
</OV_ZSOSCMODE>
<OV_AUTOLABEL> 0 1 </OV_AUTOLABEL>
<OV_AUTOLABEL> 1 1 </OV_AUTOLABEL>
<OV_AUTOLABEL> 2 1 </OV_AUTOLABEL>
<OV_X1LABELS>  S </OV_X1LABELS>
<OV_Y1LABELS>  NRF2(final), sMAF(final), NRF2_sMAF(final), NRF2_tot(final), sMAF_tot(final) </OV_Y1LABELS>
<OV_Y2LABELS>   </OV_Y2LABELS>
<OV_LEGENDXY> 0.30000001192092896 0.5 </OV_LEGENDXY>
<OV_PARAMSXY> 0.30000001192092896 0.5 </OV_PARAMSXY>
<OV_COLORTABLE> 0 <OV_COLORTABLE>
</graph.COutputView>
</SingleView>
</graph.COutputFrame>
</TabSplitter>
<idx> 1 </idx>
<TabSplitter>
<SelectedIndex> -1 </SelectedIndex>
</TabSplitter>
</jmadonna.MultiPanel>

<ChemicalReactionDialog>
<ShowRates> true </ShowRates>
<ShowConsts> true </ShowConsts>
<ShowInits> true </ShowInits>
<ShowDiffs> true </ShowDiffs>
</ChemicalReactionDialog>
</Document>
