<Document>
<Version> 22 </Version>
<JMadonnaVersion> 10.2.6 </JMadonnaVersion>
<Bounds> 0 0 1536 769 </Bounds>
<NotesEditor>
<jeditorpane>
<size>10</size><family>Tahoma</family>





</jeditorpane>
</NotesEditor>
<jmadonna.EquationPanel>
<DocPanel>
</DocPanel>
<jeditorpane>
<size>18</size><family>Serif</family>{Model V: Activation of NRF2 via nuclear exclusion of BACH1}
;Unit: time = second, concentration = nM

METHOD STIFF
STARTTIME = 0
STOPTIME = 3600 * 24
DT = 0.02
Minute = Time / 60

{Parameters}
S = 0
k1 = 100 *  logn(2) / (20 * 60)
k2 = logn(2) / (20 * 60)
k3 = 0.1		; Titration mode: k3 = 0.1, Equilibrium mode: k3 = 0.01
k4 = 0.01		; Titration mode: k4 = 0.01, Equilibrium mode: k4 = 0.1
k5 = 0.1
k6 = 0.1
k7 = 10 *  logn(2) / (60 * 60)
k8 = logn(2) / (60 * 60)
Kd7 = 1
Ki7 = 0.2

{Inintial condition}
init NRF2 = 10
init sMAF = 10
init NRF2_sMAF = 0
init BACH1c  = 0
init BACH1n  = 100     ; Titration mode: BACH1n = 100, Equilibrium mode: BACH1n = 10000
init BACH1n_sMAF = 0
init Targetgene = 0

{ODEs}
BACH1c' = k1 * BACH1n * S - k2 * BACH1c
BACH1n' = - k1 * S * BACH1n + k2 * BACH1c - k3 * BACH1n * sMAF + k4 * BACH1n_sMAF
BACH1n_sMAF' = k3 * BACH1n * sMAF - k4 * BACH1n_sMAF
NRF2' = - k5 * NRF2 * sMAF + k6 * NRF2_sMAF
NRF2_sMAF' = k5 * NRF2 * sMAF - k6 * NRF2_sMAF 
sMAF' = - k3 * BACH1n * sMAF + k4 * BACH1n_sMAF - k5 * NRF2 * sMAF + k6 * NRF2_sMAF 
Targetgene' =  k7 * NRF2_sMAF / (Kd7 * (1 + BACH1n_sMAF / Ki7) + NRF2_sMAF) - k8 * Targetgene

{Composite variables}
BACH1tot = BACH1c + BACH1n + BACH1n_sMAF
BACH1_nucleus_tot = BACH1n + BACH1n_sMAF

{Fluxes}
Flux_k1 = k1 * BACH1n * S
Flux_k2 =  k2 * BACH1c
Flux_k7 =  k7 * NRF2_sMAF / (Kd7 * (1 + BACH1n_sMAF / Ki7) + NRF2_sMAF)
Flux_k3 = k3 * BACH1n * sMAF 
Flux_k4 = k4 * BACH1n_sMAF

















<size>12</size>



</jeditorpane>
</jmadonna.EquationPanel>

<imethod> stiff </imethod>
<jmadonna.ParameterPanel>
<DocPanel>
</DocPanel>
<ParamSets>
</ParamSets>
</jmadonna.ParameterPanel>
<jmadonna.MultiPanel>
<DocPanel>
</DocPanel>
<DividerPercent> 1.0 </DividerPercent>
<Orientation> -1 </Orientation>
<idx> 0 </idx>
<TabSplitter>
<SelectedIndex> 1 </SelectedIndex>
<graph.COutputFrame>
<DocPanel>
<Name>
Graph 0
</Name>
</DocPanel>

<SingleView>
<graph.COutputView>
<Name> Graph </Name>
<GraphToolBar>
<Grid> 1 </Grid>
</GraphToolBar>
<Plot>
<LineWidth> 1 </LineWidth>
</Plot>
<OV_XVAR>
<VI_SYMBOL> Minute </VI_SYMBOL>
</OV_XVAR>
<OV_YVARS>
<OV_YVAR_I>
<VI_SYMBOL> Minute </VI_SYMBOL>
<VI_SHOW> false </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> NRF2 </VI_SYMBOL>
<VI_SHOW> false </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> sMAF </VI_SYMBOL>
<VI_SHOW> false </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> NRF2_sMAF </VI_SYMBOL>
<VI_SHOW> false </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> BACH1c </VI_SYMBOL>
<VI_SHOW> false </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> BACH1_nucleus_tot </VI_SYMBOL>
<VI_SHOW> false </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> Targetgene </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> BACH1tot </VI_SYMBOL>
<VI_SHOW> false </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
</OV_YVARS>
<OV_TABLE> false </OV_TABLE>
<OV_FFT> false </OV_FFT>
<OV_COLORS> true </OV_COLORS>
<OV_STYLES> false </OV_STYLES>
<OV_OSCMODE> false </OV_OSCMODE>
<OV_LINES> true </OV_LINES>
<OV_POINTS> true </OV_POINTS>
<OV_GRID> true </OV_GRID>
<OV_DBTN> true </OV_DBTN>
<OV_LEGEND> false </OV_LEGEND>
<OV_PARAMS> false </OV_PARAMS>
<OV_READOUT> false </OV_READOUT>
<OV_INITCOND> false </OV_INITCOND>
<OV_RDOUTFXFY> 0.0 0.0 </OV_RDOUTFXFY>
<OV_ZSNORMAL>
</OV_ZSNORMAL>
<OV_ZSFFT>
<ZS_SIZE> 1 </ZS_SIZE>
<ZS_I>
<ZS_XLOG> true </ZS_XLOG>
<ZS_Y1LOG> false </ZS_Y1LOG>
<ZS_Y2LOG> false </ZS_Y2LOG>
</ZS_I>
</OV_ZSFFT>
<OV_ZSOSCMODE>
</OV_ZSOSCMODE>
<OV_AUTOLABEL> 0 1 </OV_AUTOLABEL>
<OV_AUTOLABEL> 1 1 </OV_AUTOLABEL>
<OV_AUTOLABEL> 2 1 </OV_AUTOLABEL>
<OV_X1LABELS>  Minute </OV_X1LABELS>
<OV_Y1LABELS>  Targetgene </OV_Y1LABELS>
<OV_Y2LABELS>   </OV_Y2LABELS>
<OV_LEGENDXY> 0.372617 0.271111 </OV_LEGENDXY>
<OV_PARAMSXY> 0.372617 0.271111 </OV_PARAMSXY>
<OV_COLORTABLE> 0 <OV_COLORTABLE>
</graph.COutputView>
</SingleView>
</graph.COutputFrame>
<graph.COutputFrame>
<DocPanel>
<Name>
Parameter Plot...
</Name>
</DocPanel>
<ivar> S </ivar>
<overlay> 1 </overlay>
<paramGraph>
<nRuns> 40 </nRuns>
<initValue> 0.001 </initValue>
<finalValue> 1000.0  </finalValue>
<isArithmetic> 0 </isArithmetic>
<selectedParam> S </selectedParam>
<yvarmodel> !22!@1@#2#$!23!@1@#3#$!25!@1@#5#$!26!@1@#6#$!27!@1@#7#$%$ </yvarmodel>
</paramGraph>

<SingleView>
<graph.COutputView>
<Name> Graph </Name>
<GraphToolBar>
<Legend> 1 </Legend>
<Grid> 1 </Grid>
</GraphToolBar>
<Plot>
<LineWidth> 1 </LineWidth>
<MovableLegend>
<Bounds> 310 40 129 40 </Bounds>
<opaque> true </opaque>
<Color> 255 255 255 </Color>
<border> true </border>
</MovableLegend>
</Plot>
<OV_TABLE> false </OV_TABLE>
<OV_FFT> false </OV_FFT>
<OV_COLORS> true </OV_COLORS>
<OV_STYLES> false </OV_STYLES>
<OV_OSCMODE> false </OV_OSCMODE>
<OV_LINES> true </OV_LINES>
<OV_POINTS> true </OV_POINTS>
<OV_GRID> true </OV_GRID>
<OV_DBTN> true </OV_DBTN>
<OV_LEGEND> true </OV_LEGEND>
<OV_PARAMS> false </OV_PARAMS>
<OV_READOUT> false </OV_READOUT>
<OV_INITCOND> false </OV_INITCOND>
<OV_RDOUTFXFY> 0.0 0.0 </OV_RDOUTFXFY>
<OV_ZSNORMAL>
<ZS_SIZE> 1 </ZS_SIZE>
<ZS_I>
<ZS_XMINMAXDIV> 0.001 1000.0 6  </ZS_XMINMAXDIV>
<ZS_XLOG> true </ZS_XLOG>
<ZS_Y1MINMAXDIV> 1.0E-4 10000.0 8  </ZS_Y1MINMAXDIV>
<ZS_Y1LOG> true </ZS_Y1LOG>
<ZS_Y2LOG> false </ZS_Y2LOG>
</ZS_I>
</OV_ZSNORMAL>
<OV_ZSFFT>
<ZS_SIZE> 1 </ZS_SIZE>
<ZS_I>
<ZS_XLOG> true </ZS_XLOG>
<ZS_Y1LOG> false </ZS_Y1LOG>
<ZS_Y2LOG> false </ZS_Y2LOG>
</ZS_I>
</OV_ZSFFT>
<OV_ZSOSCMODE>
</OV_ZSOSCMODE>
<OV_AUTOLABEL> 0 1 </OV_AUTOLABEL>
<OV_AUTOLABEL> 1 1 </OV_AUTOLABEL>
<OV_AUTOLABEL> 2 1 </OV_AUTOLABEL>
<OV_X1LABELS>  S </OV_X1LABELS>
<OV_Y1LABELS>  NRF2_sMAF(final) </OV_Y1LABELS>
<OV_Y2LABELS>   </OV_Y2LABELS>
<OV_LEGENDXY> 0.30000001192092896 0.5 </OV_LEGENDXY>
<OV_PARAMSXY> 0.30000001192092896 0.5 </OV_PARAMSXY>
<OV_COLORTABLE> 0 <OV_COLORTABLE>
</graph.COutputView>
</SingleView>
</graph.COutputFrame>
</TabSplitter>
<idx> 1 </idx>
<TabSplitter>
<SelectedIndex> -1 </SelectedIndex>
</TabSplitter>
</jmadonna.MultiPanel>

<ChemicalReactionDialog>
<ShowRates> true </ShowRates>
<ShowConsts> true </ShowConsts>
<ShowInits> true </ShowInits>
<ShowDiffs> true </ShowDiffs>
</ChemicalReactionDialog>
</Document>
